export type TemplateId = 'xstore-electro' | 'live-template' | 'live-1' | 'live-2' | 'live-3' | 'modern-store' | 'modern-store-2' | 'cosmika-dark' | 'single-product' | 'fresh-market' | 'minimaliste' | 'breezel'

export interface ShopTemplate {
  id: TemplateId
  name: string
  description: string
  emoji: string
  colors: {
    primary: string
    primaryFg: string
    accent: string
    bg: string
    card: string
    cardHover: string
    text: string
    textMuted: string
    border: string
    badgeNew: string
    badgePromo: string
    cartBg: string
    headerBg: string
    filterActive: string
    filterActiveFg: string
    priceColor: string
    ctaBg: string
    ctaFg: string
    heroOverlay: string
    heroBadge: string
    heroText: string
  }
  cardStyle: {
    rounded: string
    shadow: string
    imageRounded: string
    overflow: string
    border: string
    hoverBorder: string
    hoverScale: string
    hoverY?: number
  }
  layout: {
    gridCols: string
    headerStyle: 'electro-tech' | 'luxury-dark'
    cardLayout: 'electro-card' | 'beauty'
    showCardBorder: boolean
    cardPadding: string
    imageSize: string
    badgePosition: 'top-left' | 'top-right'
    badgeStyle: 'pill' | 'rounded'
    categoryStyle: 'pill' | 'circle-image' | 'rectangle-card'
    heroStyle: 'contained' | 'full-image'
    priceStyle: 'electro-highlight' | 'beauty-elegant'
    buttonStyle: 'filled' | 'rounded'
    footerStyle: 'standard' | 'dark'
    showSearch?: boolean
    showSort?: boolean
    showCart?: boolean
  }
  decorative: {
    pattern: 'none' | 'gradient'
    gradientBg: string | null
    divider: 'line' | 'gradient'
    headerDecoration: string | null
  }
}

export const templates: Record<TemplateId, ShopTemplate> = {
  'xstore-electro': {
    id: 'xstore-electro',
    name: 'Electro Store',
    description: 'Tech moderne, accents teal, étoiles et compte à rebours',
    emoji: '📱',
    colors: {
      primary: '#10B981',
      primaryFg: '#ffffff',
      accent: '#059669',
      bg: '#f8fafc',
      card: '#ffffff',
      cardHover: '#f0fdf4',
      text: '#1e293b',
      textMuted: '#64748b',
      border: '#e2e8f0',
      badgeNew: '#10B981',
      badgePromo: '#ef4444',
      cartBg: '#ffffff',
      headerBg: '#ffffff',
      filterActive: '#10B981',
      filterActiveFg: '#ffffff',
      priceColor: '#10B981',
      ctaBg: '#10B981',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(16,185,129,0.85) 0%, rgba(5,150,105,0.7) 100%)',
      heroBadge: 'rgba(16,185,129,0.2)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '8px',
      shadow: '0 1px 6px rgba(16,185,129,0.08)',
      imageRounded: '8px 8px 0 0',
      overflow: 'hidden',
      border: '1px solid #e2e8f0',
      hoverBorder: '1px solid #10B981',
      hoverScale: 'scale(1)',
      hoverY: 0,
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4',
      headerStyle: 'electro-tech',
      cardLayout: 'electro-card',
      showCardBorder: true,
      cardPadding: 'p-3',
      imageSize: 'aspect-square',
      badgePosition: 'top-left',
      badgeStyle: 'pill',
      categoryStyle: 'pill',
      heroStyle: 'contained',
      priceStyle: 'electro-highlight',
      buttonStyle: 'filled',
      footerStyle: 'standard',
    },
    decorative: {
      pattern: 'none',
      gradientBg: 'linear-gradient(180deg, #f8fafc 0%, #f0fdf4 50%, #f8fafc 100%)',
      divider: 'line',
      headerDecoration: null,
    },
  },
  'live-template': {
    id: 'live-template',
    name: 'Live',
    description: 'Template live commerce avec badge LIVE animé, hero gradient, WhatsApp direct',
    emoji: '🎬',
    colors: {
      primary: '#FF6154',
      primaryFg: '#ffffff',
      accent: '#FF9A44',
      bg: '#FAFAFA',
      card: '#ffffff',
      cardHover: '#FFF5F3',
      text: '#1A1A2E',
      textMuted: '#6B7280',
      border: '#F3E8E7',
      badgeNew: '#FF6154',
      badgePromo: '#EF4444',
      cartBg: '#ffffff',
      headerBg: '#ffffff',
      filterActive: '#FF6154',
      filterActiveFg: '#ffffff',
      priceColor: '#FF6154',
      ctaBg: '#25D366',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(255,97,84,0.9) 0%, rgba(255,154,68,0.9) 100%)',
      heroBadge: '#EF4444',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '16px',
      shadow: '0 2px 12px rgba(255,97,84,0.08)',
      imageRounded: '16px 16px 0 0',
      overflow: 'hidden',
      border: '1px solid #F3E8E7',
      hoverBorder: '1px solid #FF6154',
      hoverScale: 'scale(1.03)',
      hoverY: -4,
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4',
      headerStyle: 'electro-tech' as const,
      cardLayout: 'electro-card' as const,
      showCardBorder: true,
      cardPadding: 'p-0',
      imageSize: 'aspect-square',
      badgePosition: 'top-right' as const,
      badgeStyle: 'pill' as const,
      categoryStyle: 'pill' as const,
      heroStyle: 'full-image' as const,
      priceStyle: 'electro-highlight' as const,
      buttonStyle: 'rounded' as const,
      footerStyle: 'dark' as const,
      showSearch: true,
      showSort: false,
      showCart: false,
    },
    decorative: {
      pattern: 'gradient' as const,
      gradientBg: 'linear-gradient(180deg, #ffffff 0%, #FFF5F3 50%, #ffffff 100%)',
      divider: 'gradient' as const,
      headerDecoration: null,
    },
  },
  'live-1': {
    id: 'live-1',
    name: 'Live 1 — Jaune/Rouge',
    description: 'Template live flashy jaune et rouge',
    emoji: '🔥',
    colors: {
      primary: '#FF6154',
      primaryFg: '#ffffff',
      accent: '#FF9A44',
      bg: '#FAFAFA',
      card: '#ffffff',
      cardHover: '#FFF5F3',
      text: '#1A1A2E',
      textMuted: '#6B7280',
      border: '#F3E8E7',
      badgeNew: '#FF6154',
      badgePromo: '#EF4444',
      cartBg: '#ffffff',
      headerBg: '#ffffff',
      filterActive: '#FF6154',
      filterActiveFg: '#ffffff',
      priceColor: '#FF6154',
      ctaBg: '#25D366',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(255,97,84,0.9) 0%, rgba(255,154,68,0.9) 100%)',
      heroBadge: '#EF4444',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '16px',
      shadow: '0 2px 12px rgba(255,97,84,0.08)',
      imageRounded: '16px 16px 0 0',
      overflow: 'hidden',
      border: '1px solid #F3E8E7',
      hoverBorder: '1px solid #FF6154',
      hoverScale: 'scale(1.03)',
      hoverY: -4,
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4',
      headerStyle: 'electro-tech' as const,
      cardLayout: 'electro-card' as const,
      showCardBorder: true,
      cardPadding: 'p-0',
      imageSize: 'aspect-square',
      badgePosition: 'top-right' as const,
      badgeStyle: 'pill' as const,
      categoryStyle: 'pill' as const,
      heroStyle: 'full-image' as const,
      priceStyle: 'electro-highlight' as const,
      buttonStyle: 'rounded' as const,
      footerStyle: 'dark' as const,
      showSearch: true,
      showSort: false,
      showCart: false,
    },
    decorative: {
      pattern: 'gradient' as const,
      gradientBg: 'linear-gradient(180deg, #ffffff 0%, #FFF5F3 50%, #ffffff 100%)',
      divider: 'gradient' as const,
      headerDecoration: null,
    },
  },
  'live-2': {
    id: 'live-2',
    name: 'Live 2 — Violet/Rose',
    description: 'Template live flashy violet et rose',
    emoji: '💜',
    colors: {
      primary: '#9333EA',
      primaryFg: '#ffffff',
      accent: '#EC4899',
      bg: '#FAFAFA',
      card: '#ffffff',
      cardHover: '#FDF4FF',
      text: '#1A1A2E',
      textMuted: '#6B7280',
      border: '#F3E8F7',
      badgeNew: '#9333EA',
      badgePromo: '#EC4899',
      cartBg: '#ffffff',
      headerBg: '#ffffff',
      filterActive: '#9333EA',
      filterActiveFg: '#ffffff',
      priceColor: '#9333EA',
      ctaBg: '#25D366',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(147,51,234,0.9) 0%, rgba(236,72,153,0.9) 100%)',
      heroBadge: '#EC4899',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '16px',
      shadow: '0 2px 12px rgba(147,51,234,0.08)',
      imageRounded: '16px 16px 0 0',
      overflow: 'hidden',
      border: '1px solid #F3E8F7',
      hoverBorder: '1px solid #9333EA',
      hoverScale: 'scale(1.03)',
      hoverY: -4,
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4',
      headerStyle: 'electro-tech' as const,
      cardLayout: 'electro-card' as const,
      showCardBorder: true,
      cardPadding: 'p-0',
      imageSize: 'aspect-square',
      badgePosition: 'top-right' as const,
      badgeStyle: 'pill' as const,
      categoryStyle: 'pill' as const,
      heroStyle: 'full-image' as const,
      priceStyle: 'electro-highlight' as const,
      buttonStyle: 'rounded' as const,
      footerStyle: 'dark' as const,
      showSearch: true,
      showSort: false,
      showCart: false,
    },
    decorative: {
      pattern: 'gradient' as const,
      gradientBg: 'linear-gradient(180deg, #ffffff 0%, #FDF4FF 50%, #ffffff 100%)',
      divider: 'gradient' as const,
      headerDecoration: null,
    },
  },
  'live-3': {
    id: 'live-3',
    name: 'Live 3 — Cyan/Orange',
    description: 'Template live flashy cyan et orange',
    emoji: '⚡',
    colors: {
      primary: '#06B6D4',
      primaryFg: '#ffffff',
      accent: '#F97316',
      bg: '#FAFAFA',
      card: '#ffffff',
      cardHover: '#ECFEFF',
      text: '#1A1A2E',
      textMuted: '#6B7280',
      border: '#E0F7FA',
      badgeNew: '#06B6D4',
      badgePromo: '#F97316',
      cartBg: '#ffffff',
      headerBg: '#ffffff',
      filterActive: '#06B6D4',
      filterActiveFg: '#ffffff',
      priceColor: '#06B6D4',
      ctaBg: '#25D366',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(6,182,212,0.9) 0%, rgba(249,115,22,0.9) 100%)',
      heroBadge: '#F97316',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '16px',
      shadow: '0 2px 12px rgba(6,182,212,0.08)',
      imageRounded: '16px 16px 0 0',
      overflow: 'hidden',
      border: '1px solid #E0F7FA',
      hoverBorder: '1px solid #06B6D4',
      hoverScale: 'scale(1.03)',
      hoverY: -4,
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4',
      headerStyle: 'electro-tech' as const,
      cardLayout: 'electro-card' as const,
      showCardBorder: true,
      cardPadding: 'p-0',
      imageSize: 'aspect-square',
      badgePosition: 'top-right' as const,
      badgeStyle: 'pill' as const,
      categoryStyle: 'pill' as const,
      heroStyle: 'full-image' as const,
      priceStyle: 'electro-highlight' as const,
      buttonStyle: 'rounded' as const,
      footerStyle: 'dark' as const,
      showSearch: true,
      showSort: false,
      showCart: false,
    },
    decorative: {
      pattern: 'gradient' as const,
      gradientBg: 'linear-gradient(180deg, #ffffff 0%, #ECFEFF 50%, #ffffff 100%)',
      divider: 'gradient' as const,
      headerDecoration: null,
    },
  },
  'modern-store': {
    id: 'modern-store',
    name: 'Modern Store',
    description: 'E-commerce moderne avec panier, checkout et WhatsApp direct',
    emoji: '🛒',
    colors: {
      primary: '#3B82F6',
      primaryFg: '#ffffff',
      accent: '#10B981',
      bg: '#ffffff',
      card: '#ffffff',
      cardHover: '#f8fafc',
      text: '#0f172a',
      textMuted: '#64748b',
      border: '#e2e8f0',
      badgeNew: '#3B82F6',
      badgePromo: '#ef4444',
      cartBg: '#ffffff',
      headerBg: '#ffffff',
      filterActive: '#3B82F6',
      filterActiveFg: '#ffffff',
      priceColor: '#10B981',
      ctaBg: '#10B981',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(59,130,246,0.85) 0%, rgba(16,185,129,0.7) 100%)',
      heroBadge: 'rgba(59,130,246,0.2)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '12px',
      shadow: '0 1px 8px rgba(59,130,246,0.08)',
      imageRounded: '12px 12px 0 0',
      overflow: 'hidden',
      border: '1px solid #e2e8f0',
      hoverBorder: '1px solid #3B82F6',
      hoverScale: 'scale(1.02)',
      hoverY: -2,
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-4',
      headerStyle: 'electro-tech',
      cardLayout: 'electro-card',
      showCardBorder: true,
      cardPadding: 'p-0',
      imageSize: 'aspect-square',
      badgePosition: 'top-left',
      badgeStyle: 'pill',
      categoryStyle: 'pill',
      heroStyle: 'full-image',
      priceStyle: 'electro-highlight',
      buttonStyle: 'rounded',
      footerStyle: 'standard',
      showSearch: true,
      showSort: false,
      showCart: true,
    },
    decorative: {
      pattern: 'none',
      gradientBg: null,
      divider: 'line',
      headerDecoration: null,
    },
  },
  'modern-store-2': {
    id: 'modern-store-2',
    name: 'Modern Store 2',
    description: 'E-commerce moderne avec hero vidéo YouTube, panier et checkout',
    emoji: '🎬',
    colors: {
      primary: '#3B82F6',
      primaryFg: '#ffffff',
      accent: '#10B981',
      bg: '#ffffff',
      card: '#ffffff',
      cardHover: '#f8fafc',
      text: '#0f172a',
      textMuted: '#64748b',
      border: '#e2e8f0',
      badgeNew: '#3B82F6',
      badgePromo: '#ef4444',
      cartBg: '#ffffff',
      headerBg: '#ffffff',
      filterActive: '#3B82F6',
      filterActiveFg: '#ffffff',
      priceColor: '#10B981',
      ctaBg: '#10B981',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(59,130,246,0.85) 0%, rgba(16,185,129,0.7) 100%)',
      heroBadge: 'rgba(59,130,246,0.2)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '12px',
      shadow: '0 1px 8px rgba(59,130,246,0.08)',
      imageRounded: '12px 12px 0 0',
      overflow: 'hidden',
      border: '1px solid #e2e8f0',
      hoverBorder: '1px solid #3B82F6',
      hoverScale: 'scale(1.02)',
      hoverY: -2,
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-4',
      headerStyle: 'electro-tech',
      cardLayout: 'electro-card',
      showCardBorder: true,
      cardPadding: 'p-0',
      imageSize: 'aspect-square',
      badgePosition: 'top-left',
      badgeStyle: 'pill',
      categoryStyle: 'pill',
      heroStyle: 'full-image',
      priceStyle: 'electro-highlight',
      buttonStyle: 'rounded',
      footerStyle: 'standard',
      showSearch: true,
      showSort: false,
      showCart: true,
    },
    decorative: {
      pattern: 'none',
      gradientBg: null,
      divider: 'line',
      headerDecoration: null,
    },
  },
  'cosmika-dark': {
    id: 'cosmika-dark',
    name: 'Cosmika Dark',
    description: 'E-commerce dark luxe avec accents dorés, marquee animé et design premium',
    emoji: '💎',
    colors: {
      primary: '#ffd21d',
      primaryFg: '#000000',
      accent: '#e7ba0a',
      bg: '#181818',
      card: '#212121',
      cardHover: '#2a2a2a',
      text: '#f8f9fb',
      textMuted: '#999999',
      border: '#333333',
      badgeNew: '#22C55E',
      badgePromo: '#EF4444',
      cartBg: '#181818',
      headerBg: '#181818',
      filterActive: '#ffd21d',
      filterActiveFg: '#000000',
      priceColor: '#ffd21d',
      ctaBg: '#ffd21d',
      ctaFg: '#000000',
      heroOverlay: 'rgba(0,0,0,0.3)',
      heroBadge: '#ffd21d',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '1rem',
      shadow: '0 2px 12px rgba(0,0,0,0.3)',
      imageRounded: '1rem 1rem 0 0',
      overflow: 'hidden',
      border: '1px solid #333333',
      hoverBorder: '1px solid rgba(255,210,29,0.3)',
      hoverScale: 'scale(1.02)',
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-4',
      headerStyle: 'luxury-dark',
      cardLayout: 'beauty',
      showCardBorder: true,
      cardPadding: 'p-0',
      imageSize: 'aspect-square',
      badgePosition: 'top-right',
      badgeStyle: 'pill',
      categoryStyle: 'pill',
      heroStyle: 'full-image',
      priceStyle: 'beauty-elegant',
      buttonStyle: 'rounded',
      footerStyle: 'dark',
      showSearch: false,
      showSort: false,
      showCart: true,
    },
    decorative: {
      pattern: 'none',
      gradientBg: null,
      divider: 'line',
      headerDecoration: null,
    },
  },
  'single-product': {
    id: 'single-product',
    name: 'Single Produit',
    description: 'Landing page optimisée conversion pour un seul produit',
    emoji: '🎯',
    colors: {
      primary: '#EC4899',
      primaryFg: '#ffffff',
      accent: '#F59E0B',
      bg: '#ffffff',
      card: '#ffffff',
      cardHover: '#fdf2f8',
      text: '#0f172a',
      textMuted: '#64748b',
      border: '#e2e8f0',
      badgeNew: '#EC4899',
      badgePromo: '#ef4444',
      cartBg: '#ffffff',
      headerBg: '#ffffff',
      filterActive: '#EC4899',
      filterActiveFg: '#ffffff',
      priceColor: '#EC4899',
      ctaBg: '#22C55E',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(236,72,153,0.85) 0%, rgba(245,158,11,0.7) 100%)',
      heroBadge: 'rgba(236,72,153,0.2)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '16px',
      shadow: '0 4px 16px rgba(236,72,153,0.1)',
      imageRounded: '16px',
      overflow: 'hidden',
      border: '1px solid #e2e8f0',
      hoverBorder: '1px solid #EC4899',
      hoverScale: 'scale(1.02)',
      hoverY: -2,
    },
    layout: {
      gridCols: 'grid-cols-1',
      headerStyle: 'luxury-dark',
      cardLayout: 'beauty',
      showCardBorder: false,
      cardPadding: 'p-6',
      imageSize: 'aspect-square',
      badgePosition: 'top-left',
      badgeStyle: 'pill',
      categoryStyle: 'pill',
      heroStyle: 'full-image',
      priceStyle: 'beauty-elegant',
      buttonStyle: 'rounded',
      footerStyle: 'dark',
    },
    decorative: {
      pattern: 'gradient',
      gradientBg: 'linear-gradient(180deg, #ffffff 0%, #fdf2f8 50%, #ffffff 100%)',
      divider: 'gradient',
      headerDecoration: null,
    },
  },
  'fresh-market': {
    id: 'fresh-market',
    name: 'Fresh Market',
    description: "Marché frais avec en-tête teal, hero orange, catégories circulaires et sections produits défilantes. Parfait pour l'alimentation, les fruits & légumes, la boulangerie et l'épicerie fine.",
    emoji: '🥬',
    colors: {
      primary: '#0D9488',
      primaryFg: '#ffffff',
      accent: '#F97316',
      bg: '#ffffff',
      card: '#ffffff',
      cardHover: '#F0FDF4',
      text: '#111827',
      textMuted: '#6B7280',
      border: '#e5e7eb',
      badgeNew: '#0D9488',
      badgePromo: '#EF4444',
      cartBg: '#ffffff',
      headerBg: '#134E4A',
      filterActive: '#0D9488',
      filterActiveFg: '#ffffff',
      priceColor: '#16A34A',
      ctaBg: '#F97316',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, #F97316 0%, #F59E0B 100%)',
      heroBadge: 'rgba(249,115,22,0.2)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '12px',
      shadow: '0 1px 6px rgba(13,148,136,0.08)',
      imageRounded: '12px 12px 0 0',
      overflow: 'hidden',
      border: '1px solid #e5e7eb',
      hoverBorder: '1px solid #0D9488',
      hoverScale: 'scale(1.02)',
      hoverY: -2,
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4',
      headerStyle: 'electro-tech',
      cardLayout: 'electro-card',
      showCardBorder: true,
      cardPadding: 'p-0',
      imageSize: 'aspect-square',
      badgePosition: 'top-left',
      badgeStyle: 'pill',
      categoryStyle: 'circle-image',
      heroStyle: 'full-image',
      priceStyle: 'electro-highlight',
      buttonStyle: 'rounded',
      footerStyle: 'dark',
      showSearch: true,
      showSort: false,
      showCart: true,
    },
    decorative: {
      pattern: 'none',
      gradientBg: null,
      divider: 'line',
      headerDecoration: null,
    },
  },
  'minimaliste': {
    id: 'minimaliste',
    name: 'Minimaliste',
    description: 'Design minimaliste Savoy : en-tête sombre, logo centré, grille 4 colonnes, slider hero',
    emoji: '✨',
    colors: {
      primary: '#1a1a1a',
      primaryFg: '#ffffff',
      accent: '#1a1a1a',
      bg: '#ffffff',
      card: '#ffffff',
      cardHover: '#f9fafb',
      text: '#111827',
      textMuted: '#6b7280',
      border: '#e5e7eb',
      badgeNew: '#111827',
      badgePromo: '#ef4444',
      cartBg: '#ffffff',
      headerBg: '#1a1a1a',
      filterActive: '#1a1a1a',
      filterActiveFg: '#ffffff',
      priceColor: '#111827',
      ctaBg: '#1a1a1a',
      ctaFg: '#ffffff',
      heroOverlay: 'rgba(0,0,0,0.3)',
      heroBadge: '#111827',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '0px',
      shadow: 'none',
      imageRounded: '0px 0px 0 0',
      overflow: 'hidden',
      border: '1px solid #e5e7eb',
      hoverBorder: '1px solid #1a1a1a',
      hoverScale: 'scale(1)',
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4',
      headerStyle: 'luxury-dark',
      cardLayout: 'beauty',
      showCardBorder: true,
      cardPadding: 'p-0',
      imageSize: 'aspect-[305/349]',
      badgePosition: 'top-left',
      badgeStyle: 'pill',
      categoryStyle: 'pill',
      heroStyle: 'full-image',
      priceStyle: 'beauty-elegant',
      buttonStyle: 'filled',
      footerStyle: 'dark',
      showSearch: true,
      showSort: false,
      showCart: true,
    },
    decorative: {
      pattern: 'none',
      gradientBg: null,
      divider: 'line',
      headerDecoration: null,
    },
  },
  'breezel': {
    id: 'breezel',
    name: 'Breezel',
    description: 'Landing page produit épurée inspirée de BreezeL : slider full-width, page produit détaillée, design navy/white',
    emoji: '🌊',
    colors: {
      primary: '#1A365D',
      primaryFg: '#ffffff',
      accent: '#1A365D',
      bg: '#ffffff',
      card: '#ffffff',
      cardHover: '#f7fafc',
      text: '#1a202c',
      textMuted: '#718096',
      border: '#e2e8f0',
      badgeNew: '#1A365D',
      badgePromo: '#e53e3e',
      cartBg: '#ffffff',
      headerBg: '#ffffff',
      filterActive: '#1A365D',
      filterActiveFg: '#ffffff',
      priceColor: '#1A365D',
      ctaBg: '#1A365D',
      ctaFg: '#ffffff',
      heroOverlay: 'rgba(26,54,93,0.3)',
      heroBadge: '#1A365D',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '0px',
      shadow: 'none',
      imageRounded: '0px',
      overflow: 'hidden',
      border: '1px solid #e2e8f0',
      hoverBorder: '1px solid #1A365D',
      hoverScale: 'scale(1)',
    },
    layout: {
      gridCols: 'grid-cols-1',
      headerStyle: 'luxury-dark',
      cardLayout: 'beauty',
      showCardBorder: false,
      cardPadding: 'p-0',
      imageSize: 'aspect-square',
      badgePosition: 'top-left',
      badgeStyle: 'pill',
      categoryStyle: 'pill',
      heroStyle: 'full-image',
      priceStyle: 'beauty-elegant',
      buttonStyle: 'filled',
      footerStyle: 'dark',
      showSearch: false,
      showSort: false,
      showCart: true,
    },
    decorative: {
      pattern: 'none',
      gradientBg: null,
      divider: 'line',
      headerDecoration: null,
    },
  },
}

export const templateList = Object.values(templates)