export type TemplateId = 'classic' | 'africa' | 'minimal' | 'elegant' | 'neon' | 'rose' | 'ocean' | 'sunset' | 'jameela' | 'xstore-fashion' | 'xstore-electro' | 'xstore-grocery' | 'electrodepot' | 'luxe-fashion' | 'tiktok-live' | 'beauty-premium'

export interface ShopTemplate {
  id: TemplateId
  name: string
  description: string
  emoji: string
  colors: {
    primary: string
    primaryFg: string
    accent: string
    bg: string
    card: string
    cardHover: string
    text: string
    textMuted: string
    border: string
    badgeNew: string
    badgePromo: string
    cartBg: string
    headerBg: string
    filterActive: string
    filterActiveFg: string
    priceColor: string
    ctaBg: string
    ctaFg: string
    heroOverlay: string
    heroBadge: string
    heroText: string
  }
  cardStyle: {
    rounded: string
    shadow: string
    imageRounded: string
    overflow: string
    border: string
    hoverBorder: string
    hoverScale: string
    hoverY?: number
  }
  layout: {
    gridCols: string // Tailwind grid classes
    headerStyle: 'standard' | 'centered' | 'minimal' | 'dark' | 'gradient' | 'elevated' | 'luxury-dark' | 'fashion-clean' | 'electro-tech' | 'grocery-fresh' | 'electrodepot-mega'
    cardLayout: 'grid' | 'list' | 'masonry' | 'compact' | 'featured' | 'beauty' | 'fashion-card' | 'electro-card' | 'grocery-card' | 'electrodepot-product'
    showCardBorder: boolean
    cardPadding: string
    imageSize: string // aspect ratio class
    badgePosition: 'top-left' | 'top-right' | 'overlay'
    badgeStyle: 'pill' | 'rounded' | 'tag'
    categoryStyle: 'pill' | 'underline' | 'button' | 'circle' | 'circle-image'
    heroStyle: 'full' | 'contained' | 'minimal' | 'dark' | 'gradient' | 'fashion-split' | 'grocery-banner' | 'electrodepot-wide'
    priceStyle: 'bold' | 'elegant' | 'minimal' | 'tag' | 'beauty-elegant' | 'fashion-bold' | 'electro-highlight'
    buttonStyle: 'filled' | 'outlined' | 'ghost' | 'rounded' | 'pill'
    footerStyle: 'standard' | 'dark' | 'minimal' | 'gradient' | 'electrodepot-footer'
  }
  decorative: {
    pattern: 'none' | 'dots' | 'lines' | 'kente' | 'waves' | 'gradient'
    gradientBg: string | null
    divider: 'line' | 'dots' | 'none' | 'gradient'
    headerDecoration: string | null // Extra header class
  }
}

export const templates: Record<TemplateId, ShopTemplate> = {
  classic: {
    id: 'classic',
    name: 'Classique',
    description: 'Thème vert WhatsApp, simple et efficace',
    emoji: '🌿',
    colors: {
      primary: '#25D366',
      primaryFg: '#ffffff',
      accent: '#128C7E',
      bg: '#ffffff',
      card: '#ffffff',
      cardHover: '#f0fdf4',
      text: '#1a1a1a',
      textMuted: '#6b7280',
      border: '#e5e7eb',
      badgeNew: '#10b981',
      badgePromo: '#f97316',
      cartBg: '#ffffff',
      headerBg: 'rgba(255,255,255,0.95)',
      filterActive: '#25D366',
      filterActiveFg: '#ffffff',
      priceColor: '#16a34a',
      ctaBg: '#25D366',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(37,211,102,0.7) 0%, rgba(18,140,126,0.8) 100%)',
      heroBadge: 'rgba(255,255,255,0.2)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '12px',
      shadow: '0 1px 3px rgba(0,0,0,0.08)',
      imageRounded: '12px 12px 0 0',
      overflow: 'hidden',
      border: 'none',
      hoverBorder: 'none',
      hoverScale: 'scale(1)',
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3',
      headerStyle: 'standard',
      cardLayout: 'grid',
      showCardBorder: false,
      cardPadding: 'p-3',
      imageSize: 'aspect-square',
      badgePosition: 'top-left',
      badgeStyle: 'pill',
      categoryStyle: 'pill',
      heroStyle: 'full',
      priceStyle: 'bold',
      buttonStyle: 'filled',
      footerStyle: 'standard',
    },
    decorative: {
      pattern: 'none',
      gradientBg: null,
      divider: 'line',
      headerDecoration: null,
    },
  },
  africa: {
    id: 'africa',
    name: 'Afrique',
    description: 'Tons chauds, terre cuite et or, motifs africains',
    emoji: '🌍',
    colors: {
      primary: '#C45D2C',
      primaryFg: '#ffffff',
      accent: '#D4A843',
      bg: '#FFF8F0',
      card: '#ffffff',
      cardHover: '#FEF3E2',
      text: '#2D1B0E',
      textMuted: '#8B6914',
      border: '#E8D5B7',
      badgeNew: '#D4A843',
      badgePromo: '#C45D2C',
      cartBg: '#FFF8F0',
      headerBg: 'rgba(255,248,240,0.95)',
      filterActive: '#C45D2C',
      filterActiveFg: '#ffffff',
      priceColor: '#C45D2C',
      ctaBg: '#C45D2C',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(196,93,44,0.75) 0%, rgba(212,168,67,0.7) 100%)',
      heroBadge: 'rgba(212,168,67,0.3)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '16px',
      shadow: '0 2px 8px rgba(196,93,44,0.1)',
      imageRounded: '16px 16px 0 0',
      overflow: 'hidden',
      border: '2px solid transparent',
      hoverBorder: '2px solid #E8D5B7',
      hoverScale: 'scale(1.02)',
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3',
      headerStyle: 'centered',
      cardLayout: 'grid',
      showCardBorder: false,
      cardPadding: 'p-4',
      imageSize: 'aspect-[4/3]',
      badgePosition: 'top-left',
      badgeStyle: 'rounded',
      categoryStyle: 'button',
      heroStyle: 'gradient',
      priceStyle: 'tag',
      buttonStyle: 'rounded',
      footerStyle: 'standard',
    },
    decorative: {
      pattern: 'kente',
      gradientBg: 'linear-gradient(180deg, #FFF8F0 0%, #FEF3E2 50%, #FFF8F0 100%)',
      divider: 'gradient',
      headerDecoration: 'border-b-2 border-dashed',
    },
  },
  minimal: {
    id: 'minimal',
    name: 'Minimaliste',
    description: 'Noir et blanc, épuré et moderne',
    emoji: '⬛',
    colors: {
      primary: '#18181b',
      primaryFg: '#ffffff',
      accent: '#52525b',
      bg: '#ffffff',
      card: '#fafafa',
      cardHover: '#f4f4f5',
      text: '#09090b',
      textMuted: '#a1a1aa',
      border: '#e4e4e7',
      badgeNew: '#18181b',
      badgePromo: '#71717a',
      cartBg: '#fafafa',
      headerBg: 'rgba(250,250,250,0.95)',
      filterActive: '#18181b',
      filterActiveFg: '#ffffff',
      priceColor: '#09090b',
      ctaBg: '#18181b',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(24,24,27,0.85) 0%, rgba(82,82,91,0.8) 100%)',
      heroBadge: 'rgba(255,255,255,0.15)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '4px',
      shadow: 'none',
      imageRounded: '4px 4px 0 0',
      overflow: 'hidden',
      border: '1px solid #e4e4e7',
      hoverBorder: '1px solid #18181b',
      hoverScale: 'scale(1)',
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3',
      headerStyle: 'minimal',
      cardLayout: 'compact',
      showCardBorder: true,
      cardPadding: 'p-2.5',
      imageSize: 'aspect-square',
      badgePosition: 'top-right',
      badgeStyle: 'tag',
      categoryStyle: 'underline',
      heroStyle: 'minimal',
      priceStyle: 'minimal',
      buttonStyle: 'ghost',
      footerStyle: 'minimal',
    },
    decorative: {
      pattern: 'none',
      gradientBg: null,
      divider: 'line',
      headerDecoration: null,
    },
  },
  elegant: {
    id: 'elegant',
    name: 'Élégant',
    description: 'Thème sombre luxe, accents dorés',
    emoji: '✨',
    colors: {
      primary: '#D4A843',
      primaryFg: '#1a1a1a',
      accent: '#B8860B',
      bg: '#0f0f0f',
      card: '#1a1a1a',
      cardHover: '#222222',
      text: '#f5f5f5',
      textMuted: '#a3a3a3',
      border: '#2a2a2a',
      badgeNew: '#D4A843',
      badgePromo: '#B8860B',
      cartBg: '#1a1a1a',
      headerBg: 'rgba(15,15,15,0.95)',
      filterActive: '#D4A843',
      filterActiveFg: '#1a1a1a',
      priceColor: '#D4A843',
      ctaBg: '#D4A843',
      ctaFg: '#1a1a1a',
      heroOverlay: 'linear-gradient(135deg, rgba(15,15,15,0.8) 0%, rgba(212,168,67,0.4) 100%)',
      heroBadge: 'rgba(212,168,67,0.25)',
      heroText: '#f5f5f5',
    },
    cardStyle: {
      rounded: '12px',
      shadow: '0 4px 12px rgba(212,168,67,0.15)',
      imageRounded: '12px 12px 0 0',
      overflow: 'hidden',
      border: '1px solid #2a2a2a',
      hoverBorder: '1px solid #D4A843',
      hoverScale: 'scale(1.02)',
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3',
      headerStyle: 'dark',
      cardLayout: 'featured',
      showCardBorder: true,
      cardPadding: 'p-4',
      imageSize: 'aspect-[3/4]',
      badgePosition: 'overlay',
      badgeStyle: 'rounded',
      categoryStyle: 'pill',
      heroStyle: 'dark',
      priceStyle: 'elegant',
      buttonStyle: 'filled',
      footerStyle: 'dark',
    },
    decorative: {
      pattern: 'gradient',
      gradientBg: 'radial-gradient(ellipse at top, rgba(212,168,67,0.05) 0%, transparent 60%)',
      divider: 'gradient',
      headerDecoration: 'border-b border-amber-900/30',
    },
  },
  neon: {
    id: 'neon',
    name: 'Neon',
    description: 'Foncé avec couleurs vibrantes, style cyber',
    emoji: '💜',
    colors: {
      primary: '#A855F7',
      primaryFg: '#ffffff',
      accent: '#06B6D4',
      bg: '#09090b',
      card: '#18181b',
      cardHover: '#1c1c22',
      text: '#f5f5f5',
      textMuted: '#a1a1aa',
      border: '#27272a',
      badgeNew: '#06B6D4',
      badgePromo: '#A855F7',
      cartBg: '#18181b',
      headerBg: 'rgba(9,9,11,0.95)',
      filterActive: '#A855F7',
      filterActiveFg: '#ffffff',
      priceColor: '#A855F7',
      ctaBg: 'linear-gradient(135deg, #A855F7, #06B6D4)',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(168,85,247,0.7) 0%, rgba(6,182,212,0.7) 100%)',
      heroBadge: 'rgba(168,85,247,0.25)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '16px',
      shadow: '0 0 20px rgba(168,85,247,0.1)',
      imageRounded: '16px 16px 0 0',
      overflow: 'hidden',
      border: '1px solid #27272a',
      hoverBorder: '1px solid #A855F7',
      hoverScale: 'scale(1.03)',
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3',
      headerStyle: 'dark',
      cardLayout: 'grid',
      showCardBorder: true,
      cardPadding: 'p-3',
      imageSize: 'aspect-square',
      badgePosition: 'top-left',
      badgeStyle: 'pill',
      categoryStyle: 'pill',
      heroStyle: 'gradient',
      priceStyle: 'bold',
      buttonStyle: 'filled',
      footerStyle: 'dark',
    },
    decorative: {
      pattern: 'gradient',
      gradientBg: 'radial-gradient(ellipse at bottom right, rgba(168,85,247,0.08) 0%, transparent 60%)',
      divider: 'gradient',
      headerDecoration: 'border-b border-purple-900/30',
    },
  },
  rose: {
    id: 'rose',
    name: 'Rose',
    description: 'Doux et romantique, parfait pour la mode et beauté',
    emoji: '🌸',
    colors: {
      primary: '#EC4899',
      primaryFg: '#ffffff',
      accent: '#F9A8D4',
      bg: '#FFF1F8',
      card: '#ffffff',
      cardHover: '#FDF2F8',
      text: '#1a1a2e',
      textMuted: '#be185d',
      border: '#F9A8D4',
      badgeNew: '#EC4899',
      badgePromo: '#F43F5E',
      cartBg: '#FFF1F8',
      headerBg: 'rgba(255,241,248,0.95)',
      filterActive: '#EC4899',
      filterActiveFg: '#ffffff',
      priceColor: '#EC4899',
      ctaBg: '#EC4899',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(236,72,153,0.7) 0%, rgba(249,168,212,0.7) 100%)',
      heroBadge: 'rgba(236,72,153,0.25)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '20px',
      shadow: '0 2px 12px rgba(236,72,153,0.1)',
      imageRounded: '20px 20px 0 0',
      overflow: 'hidden',
      border: 'none',
      hoverBorder: 'none',
      hoverScale: 'scale(1.02)',
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3',
      headerStyle: 'centered',
      cardLayout: 'grid',
      showCardBorder: false,
      cardPadding: 'p-3',
      imageSize: 'aspect-[3/4]',
      badgePosition: 'top-left',
      badgeStyle: 'rounded',
      categoryStyle: 'pill',
      heroStyle: 'gradient',
      priceStyle: 'bold',
      buttonStyle: 'pill',
      footerStyle: 'standard',
    },
    decorative: {
      pattern: 'dots',
      gradientBg: 'radial-gradient(circle at top left, rgba(236,72,153,0.06) 0%, transparent 50%)',
      divider: 'gradient',
      headerDecoration: null,
    },
  },
  ocean: {
    id: 'ocean',
    name: 'Océan',
    description: 'Bleu profond et apaisant, style frais et professionnel',
    emoji: '🌊',
    colors: {
      primary: '#0891B2',
      primaryFg: '#ffffff',
      accent: '#06B6D4',
      bg: '#F0F9FF',
      card: '#ffffff',
      cardHover: '#ECFEFF',
      text: '#0c4a6e',
      textMuted: '#0e7490',
      border: '#BAE6FD',
      badgeNew: '#0891B2',
      badgePromo: '#0284C7',
      cartBg: '#F0F9FF',
      headerBg: 'rgba(240,249,255,0.95)',
      filterActive: '#0891B2',
      filterActiveFg: '#ffffff',
      priceColor: '#0E7490',
      ctaBg: '#0891B2',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(8,145,178,0.75) 0%, rgba(6,182,212,0.7) 100%)',
      heroBadge: 'rgba(8,145,178,0.25)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '12px',
      shadow: '0 1px 6px rgba(8,145,178,0.1)',
      imageRounded: '12px 12px 0 0',
      overflow: 'hidden',
      border: '1px solid #BAE6FD',
      hoverBorder: '1px solid #0891B2',
      hoverScale: 'scale(1.01)',
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3',
      headerStyle: 'standard',
      cardLayout: 'grid',
      showCardBorder: true,
      cardPadding: 'p-3',
      imageSize: 'aspect-square',
      badgePosition: 'top-right',
      badgeStyle: 'pill',
      categoryStyle: 'pill',
      heroStyle: 'contained',
      priceStyle: 'bold',
      buttonStyle: 'filled',
      footerStyle: 'standard',
    },
    decorative: {
      pattern: 'waves',
      gradientBg: 'linear-gradient(180deg, #F0F9FF 0%, #E0F2FE 100%)',
      divider: 'line',
      headerDecoration: null,
    },
  },
  jameela: {
    id: 'jameela',
    name: 'Jameela Beauty',
    description: 'Luxe épuré, accents dorés, beauté professionnelle',
    emoji: '💎',
    colors: {
      primary: '#C8A882',
      primaryFg: '#1a1a1a',
      accent: '#b8956a',
      bg: '#ffffff',
      card: '#ffffff',
      cardHover: '#fafafa',
      text: '#1a1a1a',
      textMuted: '#666666',
      border: '#f0f0f0',
      badgeNew: '#ffa502',
      badgePromo: '#ff4757',
      cartBg: '#ffffff',
      headerBg: '#1a1a1a',
      filterActive: '#C8A882',
      filterActiveFg: '#1a1a1a',
      priceColor: '#C8A882',
      ctaBg: '#C9788F',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(26,26,26,0.75) 0%, rgba(200,168,130,0.6) 100%)',
      heroBadge: 'rgba(200,168,130,0.3)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '8px',
      shadow: '0 2px 8px rgba(0,0,0,0.06)',
      imageRounded: '8px 8px 0 0',
      overflow: 'hidden',
      border: 'none',
      hoverBorder: 'none',
      hoverScale: 'scale(1)',
      hoverY: -5,
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-4',
      headerStyle: 'luxury-dark',
      cardLayout: 'beauty',
      showCardBorder: false,
      cardPadding: 'p-3',
      imageSize: 'aspect-square',
      badgePosition: 'top-left',
      badgeStyle: 'pill',
      categoryStyle: 'underline',
      heroStyle: 'full',
      priceStyle: 'beauty-elegant',
      buttonStyle: 'rounded',
      footerStyle: 'standard',
    },
    decorative: {
      pattern: 'none',
      gradientBg: null,
      divider: 'none',
      headerDecoration: null,
    },
  },
  'xstore-fashion': {
    id: 'xstore-fashion',
    name: 'Fashion Store',
    description: 'Style élégant, accents rouges, mode et tendance',
    emoji: '👗',
    colors: {
      primary: '#C8102E',
      primaryFg: '#ffffff',
      accent: '#333333',
      bg: '#ffffff',
      card: '#ffffff',
      cardHover: '#f9f9f9',
      text: '#222222',
      textMuted: '#777777',
      border: '#e8e8e8',
      badgeNew: '#C8102E',
      badgePromo: '#ff4757',
      cartBg: '#ffffff',
      headerBg: '#ffffff',
      filterActive: '#C8102E',
      filterActiveFg: '#ffffff',
      priceColor: '#C8102E',
      ctaBg: '#222222',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(200,16,46,0.8) 0%, rgba(34,34,34,0.6) 100%)',
      heroBadge: 'rgba(200,16,46,0.2)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '4px',
      shadow: '0 1px 4px rgba(0,0,0,0.06)',
      imageRounded: '4px 4px 0 0',
      overflow: 'hidden',
      border: '1px solid #e8e8e8',
      hoverBorder: '1px solid #C8102E',
      hoverScale: 'scale(1)',
      hoverY: -3,
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4',
      headerStyle: 'fashion-clean',
      cardLayout: 'fashion-card',
      showCardBorder: true,
      cardPadding: 'p-3',
      imageSize: 'aspect-[3/4]',
      badgePosition: 'top-left',
      badgeStyle: 'pill',
      categoryStyle: 'circle-image',
      heroStyle: 'fashion-split',
      priceStyle: 'fashion-bold',
      buttonStyle: 'filled',
      footerStyle: 'minimal',
    },
    decorative: {
      pattern: 'none',
      gradientBg: null,
      divider: 'line',
      headerDecoration: null,
    },
  },
  'xstore-electro': {
    id: 'xstore-electro',
    name: 'Electro Store',
    description: 'Tech moderne, accents teal, étoiles et compte à rebours',
    emoji: '📱',
    colors: {
      primary: '#10B981',
      primaryFg: '#ffffff',
      accent: '#059669',
      bg: '#f8fafc',
      card: '#ffffff',
      cardHover: '#f0fdf4',
      text: '#1e293b',
      textMuted: '#64748b',
      border: '#e2e8f0',
      badgeNew: '#10B981',
      badgePromo: '#ef4444',
      cartBg: '#ffffff',
      headerBg: '#ffffff',
      filterActive: '#10B981',
      filterActiveFg: '#ffffff',
      priceColor: '#10B981',
      ctaBg: '#10B981',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(16,185,129,0.85) 0%, rgba(5,150,105,0.7) 100%)',
      heroBadge: 'rgba(16,185,129,0.2)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '8px',
      shadow: '0 1px 6px rgba(16,185,129,0.08)',
      imageRounded: '8px 8px 0 0',
      overflow: 'hidden',
      border: '1px solid #e2e8f0',
      hoverBorder: '1px solid #10B981',
      hoverScale: 'scale(1)',
      hoverY: 0,
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3 lg:grid-cols-4',
      headerStyle: 'electro-tech',
      cardLayout: 'electro-card',
      showCardBorder: true,
      cardPadding: 'p-3',
      imageSize: 'aspect-square',
      badgePosition: 'top-left',
      badgeStyle: 'pill',
      categoryStyle: 'pill',
      heroStyle: 'contained',
      priceStyle: 'electro-highlight',
      buttonStyle: 'filled',
      footerStyle: 'standard',
    },
    decorative: {
      pattern: 'none',
      gradientBg: 'linear-gradient(180deg, #f8fafc 0%, #f0fdf4 50%, #f8fafc 100%)',
      divider: 'line',
      headerDecoration: null,
    },
  },
  'xstore-grocery': {
    id: 'xstore-grocery',
    name: 'Grocery Store',
    description: 'Fraîcheur alimentaire, vert vibrant, livraison et promotions',
    emoji: '🥬',
    colors: {
      primary: '#00A651',
      primaryFg: '#ffffff',
      accent: '#ff4757',
      bg: '#ffffff',
      card: '#ffffff',
      cardHover: '#f0fdf4',
      text: '#1a1a1a',
      textMuted: '#666666',
      border: '#e0e0e0',
      badgeNew: '#00A651',
      badgePromo: '#ff4757',
      cartBg: '#ffffff',
      headerBg: '#ffffff',
      filterActive: '#00A651',
      filterActiveFg: '#ffffff',
      priceColor: '#00A651',
      ctaBg: '#00A651',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(0,166,81,0.85) 0%, rgba(0,120,60,0.7) 100%)',
      heroBadge: 'rgba(0,166,81,0.25)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '12px',
      shadow: '0 2px 8px rgba(0,166,81,0.08)',
      imageRounded: '12px 12px 0 0',
      overflow: 'hidden',
      border: '1px solid #e0e0e0',
      hoverBorder: '1px solid #00A651',
      hoverScale: 'scale(1.02)',
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3',
      headerStyle: 'grocery-fresh',
      cardLayout: 'grocery-card',
      showCardBorder: true,
      cardPadding: 'p-3',
      imageSize: 'aspect-square',
      badgePosition: 'top-right',
      badgeStyle: 'rounded',
      categoryStyle: 'circle',
      heroStyle: 'grocery-banner',
      priceStyle: 'bold',
      buttonStyle: 'rounded',
      footerStyle: 'standard',
    },
    decorative: {
      pattern: 'none',
      gradientBg: null,
      divider: 'line',
      headerDecoration: null,
    },
  },
  sunset: {
    id: 'sunset',
    name: 'Coucher de soleil',
    description: 'Dégradé chaud orange-violet, énergie vibrante',
    emoji: '🌅',
    colors: {
      primary: '#F97316',
      primaryFg: '#ffffff',
      accent: '#8B5CF6',
      bg: '#FFFBF5',
      card: '#ffffff',
      cardHover: '#FFF7ED',
      text: '#1c1917',
      textMuted: '#92400e',
      border: '#FED7AA',
      badgeNew: '#8B5CF6',
      badgePromo: '#F97316',
      cartBg: '#FFFBF5',
      headerBg: 'rgba(255,251,245,0.95)',
      filterActive: 'linear-gradient(135deg, #F97316, #8B5CF6)',
      filterActiveFg: '#ffffff',
      priceColor: '#F97316',
      ctaBg: 'linear-gradient(135deg, #F97316, #8B5CF6)',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(249,115,22,0.75) 0%, rgba(139,92,246,0.7) 100%)',
      heroBadge: 'rgba(249,115,22,0.25)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '14px',
      shadow: '0 2px 10px rgba(249,115,22,0.1)',
      imageRounded: '14px 14px 0 0',
      overflow: 'hidden',
      border: 'none',
      hoverBorder: 'none',
      hoverScale: 'scale(1.03)',
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3',
      headerStyle: 'gradient',
      cardLayout: 'grid',
      showCardBorder: false,
      cardPadding: 'p-3',
      imageSize: 'aspect-square',
      badgePosition: 'top-left',
      badgeStyle: 'pill',
      categoryStyle: 'pill',
      heroStyle: 'gradient',
      priceStyle: 'bold',
      buttonStyle: 'pill',
      footerStyle: 'standard',
    },
    decorative: {
      pattern: 'gradient',
      gradientBg: 'linear-gradient(180deg, #FFFBF5 0%, #FFF7ED 50%, #F5F3FF 100%)',
      divider: 'gradient',
      headerDecoration: 'border-b border-orange-200/50',
    },
  },
  electrodepot: {
    id: 'electrodepot',
    name: 'ElectroDépôt',
    description: 'Méga-store électronique, promo barre, large slider, marques, newsletter',
    emoji: '🔌',
    colors: {
      primary: '#E31837',
      primaryFg: '#ffffff',
      accent: '#1a1a2e',
      bg: '#ffffff',
      card: '#ffffff',
      cardHover: '#f9f9f9',
      text: '#1a1a1a',
      textMuted: '#666666',
      border: '#e0e0e0',
      badgeNew: '#E31837',
      badgePromo: '#ff6b00',
      cartBg: '#ffffff',
      headerBg: '#ffffff',
      filterActive: '#E31837',
      filterActiveFg: '#ffffff',
      priceColor: '#E31837',
      ctaBg: '#E31837',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(227,24,55,0.85) 0%, rgba(26,26,46,0.75) 100%)',
      heroBadge: 'rgba(227,24,55,0.2)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '4px',
      shadow: '0 1px 4px rgba(0,0,0,0.08)',
      imageRounded: '4px 4px 0 0',
      overflow: 'hidden',
      border: '1px solid #e0e0e0',
      hoverBorder: '1px solid #E31837',
      hoverScale: 'scale(1)',
      hoverY: -4,
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3 lg:grid-cols-5',
      headerStyle: 'electrodepot-mega',
      cardLayout: 'electrodepot-product',
      showCardBorder: true,
      cardPadding: 'p-2',
      imageSize: 'aspect-square',
      badgePosition: 'top-left',
      badgeStyle: 'pill',
      categoryStyle: 'circle',
      heroStyle: 'electrodepot-wide',
      priceStyle: 'electro-highlight',
      buttonStyle: 'filled',
      footerStyle: 'electrodepot-footer',
    },
    decorative: {
      pattern: 'none',
      gradientBg: null,
      divider: 'line',
      headerDecoration: null,
    },
  },
  'luxe-fashion': {
    id: 'luxe-fashion',
    name: 'Luxe Fashion',
    description: 'Glassmorphism champagne doré, stories Instagram, effet waahou garanti',
    emoji: '✨',
    colors: {
      primary: '#D4AF37',
      primaryFg: '#1a1a1a',
      accent: '#C9A96E',
      bg: '#FFFDD0',
      card: 'rgba(255,255,255,0.25)',
      cardHover: 'rgba(255,255,255,0.4)',
      text: '#1a1a1a',
      textMuted: '#8B7355',
      border: 'rgba(212,175,55,0.2)',
      badgeNew: '#D4AF37',
      badgePromo: '#E8475F',
      cartBg: 'rgba(255,255,255,0.85)',
      headerBg: 'rgba(255,221,208,0.7)',
      filterActive: '#D4AF37',
      filterActiveFg: '#1a1a1a',
      priceColor: '#B8860B',
      ctaBg: '#25D366',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(212,175,55,0.6) 0%, rgba(255,229,229,0.7) 100%)',
      heroBadge: 'rgba(212,175,55,0.3)',
      heroText: '#1a1a1a',
    },
    cardStyle: {
      rounded: '20px',
      shadow: '0 8px 32px rgba(212,175,55,0.15)',
      imageRounded: '20px 20px 0 0',
      overflow: 'hidden',
      border: '1px solid rgba(255,255,255,0.3)',
      hoverBorder: '1px solid rgba(212,175,55,0.5)',
      hoverScale: 'scale(1.03)',
      hoverY: -5,
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3',
      headerStyle: 'gradient',
      cardLayout: 'fashion-card',
      showCardBorder: false,
      cardPadding: 'p-3',
      imageSize: 'aspect-[3/4]',
      badgePosition: 'top-right',
      badgeStyle: 'pill',
      categoryStyle: 'circle-image',
      heroStyle: 'fashion-split',
      priceStyle: 'elegant',
      buttonStyle: 'pill',
      footerStyle: 'minimal',
    },
    decorative: {
      pattern: 'gradient',
      gradientBg: 'linear-gradient(135deg, #FFE5E5 0%, #FFFDD0 50%, #FFE5E5 100%)',
      divider: 'gradient',
      headerDecoration: null,
    },
  },
  'tiktok-live': {
    id: 'tiktok-live',
    name: 'TikTok Live',
    description: 'Ultra-dynamique, LIVE en direct, urgence et conversion maximale',
    emoji: '🔴',
    colors: {
      primary: '#FF0050',
      primaryFg: '#ffffff',
      accent: '#25F4EE',
      bg: '#0a0a0a',
      card: '#1a1a1a',
      cardHover: '#222222',
      text: '#ffffff',
      textMuted: '#aaaaaa',
      border: '#333333',
      badgeNew: '#FF0050',
      badgePromo: '#FE2C55',
      cartBg: '#1a1a1a',
      headerBg: 'rgba(10,10,10,0.95)',
      filterActive: '#FF0050',
      filterActiveFg: '#ffffff',
      priceColor: '#FF0050',
      ctaBg: 'linear-gradient(135deg, #25D366, #128C7E)',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(255,0,80,0.85) 0%, rgba(254,44,85,0.7) 100%)',
      heroBadge: 'rgba(255,0,80,0.3)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '16px',
      shadow: '0 4px 20px rgba(255,0,80,0.2)',
      imageRounded: '16px 16px 0 0',
      overflow: 'hidden',
      border: '1px solid #333333',
      hoverBorder: '1px solid #FF0050',
      hoverScale: 'scale(1.02)',
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3',
      headerStyle: 'dark',
      cardLayout: 'grid',
      showCardBorder: true,
      cardPadding: 'p-3',
      imageSize: 'aspect-square',
      badgePosition: 'top-right',
      badgeStyle: 'pill',
      categoryStyle: 'pill',
      heroStyle: 'gradient',
      priceStyle: 'bold',
      buttonStyle: 'pill',
      footerStyle: 'dark',
    },
    decorative: {
      pattern: 'gradient',
      gradientBg: 'radial-gradient(ellipse at top, rgba(255,0,80,0.08) 0%, transparent 60%)',
      divider: 'gradient',
      headerDecoration: null,
    },
  },
  'beauty-premium': {
    id: 'beauty-premium',
    name: 'Beauty Premium',
    description: 'Éditorial Sephora/Glossier, rose gold, masonry, confiance totale',
    emoji: '💖',
    colors: {
      primary: '#B76E79',
      primaryFg: '#ffffff',
      accent: '#DCAE96',
      bg: '#FFFFF0',
      card: '#ffffff',
      cardHover: '#FFF8F5',
      text: '#36454F',
      textMuted: '#8B7E74',
      border: '#F0E6E0',
      badgeNew: '#B76E79',
      badgePromo: '#E8475F',
      cartBg: '#ffffff',
      headerBg: 'rgba(255,255,240,0.95)',
      filterActive: '#B76E79',
      filterActiveFg: '#ffffff',
      priceColor: '#B76E79',
      ctaBg: '#B76E79',
      ctaFg: '#ffffff',
      heroOverlay: 'linear-gradient(135deg, rgba(183,110,121,0.75) 0%, rgba(220,174,150,0.7) 100%)',
      heroBadge: 'rgba(183,110,121,0.25)',
      heroText: '#ffffff',
    },
    cardStyle: {
      rounded: '16px',
      shadow: '0 2px 12px rgba(183,110,121,0.1)',
      imageRounded: '16px 16px 0 0',
      overflow: 'hidden',
      border: 'none',
      hoverBorder: 'none',
      hoverScale: 'scale(1)',
      hoverY: -5,
    },
    layout: {
      gridCols: 'grid-cols-2 md:grid-cols-3',
      headerStyle: 'centered',
      cardLayout: 'beauty',
      showCardBorder: false,
      cardPadding: 'p-3',
      imageSize: 'aspect-[3/4]',
      badgePosition: 'top-left',
      badgeStyle: 'rounded',
      categoryStyle: 'underline',
      heroStyle: 'fashion-split',
      priceStyle: 'beauty-elegant',
      buttonStyle: 'rounded',
      footerStyle: 'standard',
    },
    decorative: {
      pattern: 'dots',
      gradientBg: 'radial-gradient(circle at top left, rgba(183,110,121,0.04) 0%, transparent 50%)',
      divider: 'line',
      headerDecoration: null,
    },
  },
}

export const templateList = Object.values(templates)
